
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppTheme from "@/components/theme/AppTheme";
import { UserContextProvider } from "@/context/userContext";
import QueryProvider from "@/components/query-provider";
const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <UserContextProvider>
        <QueryProvider>
          <AppTheme>{children}</AppTheme>
        </QueryProvider>
        </UserContextProvider>

      </body>
    </html>
  );
}
