name: Run Cron Job Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-cronjob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # Change version if needed

      - name: Install Dependencies
        run: npm install

      - name: Create .env File
        run: |
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" >> .env
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "FIREBASE_PRIVATE_KEY=\"${{ secrets.FIREBASE_PRIVATE_KEY }}\"" >> .env

      - name: Run Script
        run: node index.js
